language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run reconCNV.py -x data/hg19_genome_length.txt -c config.json -r data/sample_data/HT-29.cnr  -d . -o test.html -f -g data/sample_data/HT-29.genemetrics.cns -s data/sample_data/HT-29.cns -v data/sample_data/HT-29.vcf -b data/artifact_SNP.bed -t data/artifact_seg.bed -a data/hg19_COSMIC_genes_model.txt -p 0.95 -l 3.04 -z male -y -0.4 -j
after_success:
  - codecov